name: 🐞 Bug Report
description: File a bug/issue
title: "***The title of your Issue here***"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Are you using the latest version of STIG Manager?
    description: The STIGMan project is in development using an agile process that releases new features and bugfixes frequently.  
    options:
    - label: I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases)
      required: true      
- type: dropdown
  id: issue-location
  attributes:
    multiple: true
    label: Where are you experiencing the issue?
    options:
     - API
     - UI or other client
     - Deployment
     - Elsewhere
- type: textarea
  attributes:
    label: Current Behavior
    description: A description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Can you provide screenshots, logs, or other useful artifacts?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe your Environment
    description: |
      examples:
        - **Hosting**: Are you hosting your own deployment of STIGMan or being provided with an instance? 
        - **Browser**: Chrome
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - Hosting:
        - Browser:
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false    