version: '3.7'

# STIG Manager docker-compose orchestration
# Maintainer: carl.a.smigielski@saic.com

services:
  db:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    volumes:
      - ./stigman-init:/stigman-init
      ports:
        - "1521:1521"      
  web:
    image: stigman-classic:basic
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./stigman-init:/stigman-init
    environment:
      - SM_ORACLE_HOST=db
    init: true
    ports:
      - "55443:443"
    depends_on:
      - db