name: Example workflow for Node using Snyk 
on: 
  workflow_dispatch:
  
  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
        with: 
          args: --file=/api/source/package-lock.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
